version: '3'

services:
  db:
    networks:
        test:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'mits'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'trisys123'
       MYSQL_ROOT_PASSWORD: 'trisys123'
  web:
    networks:
        test:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db 

networks:
    test:
        driver: bridge