# Generated by Django 3.2.6 on 2021-08-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('mnf_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineIntakeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_time', models.CharField(choices=[('morning', 'morning'), ('night', 'night'), ('afternoon', 'afternoon')], max_length=20)),
                ('times_a_day', models.IntegerField()),
                ('day_in_week', models.CharField(choices=[('everyday', 'everyday'), ('weekday', 'weekday'), ('weekend', 'weekend'), ('alternate_day', 'alternate_day')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mits_app.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mits_app.users')),
            ],
        ),
    ]
