# Generated by Django 3.2.6 on 2021-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mits_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineintakeschedule',
            name='day_in_week',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicineintakeschedule',
            name='intake_time',
            field=models.CharField(max_length=20),
        ),
    ]
