# Generated by Django 3.2.6 on 2021-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mits_app', '0002_auto_20210826_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineintakeschedule',
            name='quantity_per_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
