# Generated by Django 3.2.6 on 2021-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mits_app', '0003_medicineintakeschedule_quantity_per_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineintakeschedule',
            name='status',
            field=models.CharField(default='started', max_length=20),
        ),
    ]
