# Generated by Django 3.2.6 on 2021-08-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mits_app', '0005_auto_20210827_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity_measurment',
            field=models.CharField(choices=[('piece', 'piece'), ('ml', 'ml')], default='piece', max_length=20, null=True),
        ),
    ]
